### ISSUE TITLE
Common permissions require deprecated provider syntax

### ISSUE THREAD

**Issue by kpeters-cbsi** [AntonBazhal/serverless-plugin-custom-roles#16]
Serverless have deprecated this syntax for specifying IAM role statements in the `provider` section of `serverless.yml`:

```yaml
provider:
  name: aws
  iamRoleStatements:
    - Effect: Allow
      Action: service:Action
      Resource: arn:aws:service:us-east-1:123456789012:something/*
``` 

in favor of:

```yaml
provider:
  name: aws
  iam:
    role:
      statements:
        - Effect: Allow
          Action: service:Action
          Resource: arn:aws:service:us-east-1:123456789012:something/*
``` 

However, this plugin still requires the deprecated syntax in order to add permissions common to all functions.
