### ISSUE TITLE
add support for cloudformation functions (ImportValue in particular) in arn

### ISSUE THREAD

**Issue by jcdietrich** [AntonBazhal/serverless-plugin-custom-roles#2]
I need to set the arn using an exported value set in another stack. 

```yml
assignLearningStreamListener:
    handler: src/handlers/assignLearningStreamListener.handler
    events:
        - stream:
            batchSize: 1000
            type: dynamodb
            arn:
                Fn::ImportValue: "assignedLearning-${self:custom.stage}-stream-arn"
```
This warns as follows:
```
Serverless: [serverless-plugin-custom-roles]: WARNING: Stream event source for function
'assignLearningStreamListener' is not configured properly.
IAM permissions will not be set properly.
```
I think I have it working despite this warning.

**Comment by chris-feist** [comment]
This also warns when the arn uses the get attribute function:
```yaml
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - MyDynamoDBTable
              - StreamArn
```
