### ISSUE TITLE
Implicit permissions SQS disappear. 

### ISSUE THREAD

**Issue by jlgouwyapizr** [AntonBazhal/serverless-plugin-custom-roles#25]
Hey Folks, 

I have this lambda which listens a SQS : 

```
listenMediaGrabs:
    handler: src/handler/classifieds/listen-media-grabs.handler
    name: ${self:provider.stage}-${self:service}-listenMediaGrabs
    events:
      - sqs:
          arn: { "Fn::Join" : [":", ["arn:aws:sqs:${self:provider.region}", { "Ref" : "AWS::AccountId" }, "${self:provider.stage}-classified-service-media-grabs-available.fifo"]]  }
          batchSize: 1

```

Without the plugin, when i deploy the serverless stack, I see thoses permissions on the lambda :
- sqs:ReceiveMessage
- sqs:DeleteMessage
- sqs:GetQueueAttributes 

those permissions are handled by serverless in the background. All is working fine. My SQS is read. 

But once we use the plugin, we didn't have anymore thoses permissions at all. 
The result : that breaks the lambda because the sqs is never read anymore.

How to fix that ? Do we need to have more explicit ?
Why thoses permissions disappear ? 

Thanks
