### ISSUE TITLE
Lambda@Edge support?

### ISSUE THREAD

**Issue by LinguineCode** [AntonBazhal/serverless-plugin-custom-roles#9]
Hello and thanks for your plugin, I use it every day

I have recently been tasked with creating a Lambda@Edge configuration using `serverless-framework`. It requires an IAM policy with an additional Service Principal of `edgelambda.amazonaws.com`. Any ideas on how to use this plugin to get that IAM policy? 

Check it out below:

```
{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Effect": "Allow",
         "Principal": {
            "Service": [
               "lambda.amazonaws.com",
               "edgelambda.amazonaws.com"
            ]
         },
         "Action": "sts:AssumeRole"
      }
   ]
}
```
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-permissions.html

**Comment by AntonBazhal** [comment]
Hello, this plugin can be extended with a config option to include `edgelambda.amazonaws.com` as an additional principal. PRs are always welcome)

**Comment by solsglasses** [comment]
Thanks. I'm not a programmer but if anyone stumbles on this issue and they are able to help:

The additional Service Principal should not be added by default. A user would have to specify that this particular function is for Lambda@Edge, and the role should use a different Statement.

Maybe like this?

```
provider:
  name: aws
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource: "*"

### PROPOSED USAGE:
  iamRoleStatementsLambdaEdge:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: "*"
```

With `iamRoleStatementsLambdaEdge` ensuring that the role's policy statement is copied from the original post
